def parse_transcript_to_nfr(text, overrides, profile):
    # TODO: Customize per client
    return {
        "Summary": "Autogenerated summary placeholder",
        "Key Risks": ["Placeholder risk"],
        "Notes": text[:200]
    }
