# ============================================================
# client_filesystem.py — Auto-Creates Full Client & Project Structure
# ScopeSight PMO Tools (NFR • RAIDs • Actions • Dashboards)
# ============================================================

import json
import re
import unicodedata
from pathlib import Path
from datetime import datetime


# Root of all client folders
BASE_PATH = Path("clients")


# ============================================================
# NEW: SAFE NAME HELPERS
# ============================================================

def safe_fs_name(text: str) -> str:
    """
    Converts any string into a filesystem-safe, ASCII-only name:
    - Removes accents
    - Replaces spaces with underscores
    - Keeps alphanumeric + underscores only
    """
    if not text:
        return ""

    # Normalize accents → ASCII
    text = unicodedata.normalize("NFKD", text)
    text = text.encode("ascii", "ignore").decode()

    # Lowercase
    text = text.lower().strip()

    # Replace spaces/dashes with underscores
    text = re.sub(r"[\s\-]+", "_", text)

    # Remove illegal characters
    text = re.sub(r"[^a-z0-9_]+", "", text)

    return text


def normalise_client_name(text: str) -> str:
    """
    Canonical internal identifier for loaders, profiles, NFR generator.
    Allows wider unicode but still cleans dangerous characters.
    """
    if not text:
        return ""

    text = text.strip().lower()
    text = text.replace(" ", "_")
    text = re.sub(r"[^a-z0-9_]+", "", text)

    return text


# ------------------------------------------------------------
# Helper — ensure folder
# ------------------------------------------------------------
def _ensure(path: Path):
    path.mkdir(parents=True, exist_ok=True)


# ------------------------------------------------------------
# Write a file if it does not exist
# ------------------------------------------------------------
def _write_if_missing(path: Path, content: str | bytes):
    if not path.exists():
        if isinstance(content, bytes):
            path.write_bytes(content)
        else:
            path.write_text(content)


# ------------------------------------------------------------
# Generate skeleton parsers and dashboard files
# ------------------------------------------------------------
PARSER_STUB = """\
def parse_transcript_to_nfr(text, overrides, profile):
    # TODO: Customize per client
    return {
        "Summary": "Autogenerated summary placeholder",
        "Key Risks": ["Placeholder risk"],
        "Notes": text[:200]
    }
"""

RAID_PARSER_STUB = """\
def parse_raid_input(input_text, config):
    # TODO: Customize for client RAID logic
    return {
        "Risks": [],
        "Issues": [],
        "Dependencies": [],
        "Actions": []
    }
"""

ACTION_PARSER_STUB = """\
def parse_action_input(input_text, config):
    # TODO: Customize for client action parsing
    return {
        "Actions": []
    }
"""

DASHBOARD_STUB = """\
def get_dashboard_settings():
    # Example dashboard settings
    return {
        "theme": "default",
        "layout": "standard"
    }
"""

PLACEHOLDER_DOCX = "Placeholder file - replace with real template"


# ------------------------------------------------------------
# Create full CLIENT folder structure
# ------------------------------------------------------------
def ensure_client_folder(client_code: str):
    """
    Ensures clients/<client_code>/ exists and contains:
    - client_config.json
    - parser stubs
    - templates
    - output folders
    """

    root = BASE_PATH / client_code
    _ensure(root)

    # Python package init
    _write_if_missing(root / "__init__.py", "# Auto-created client package\n")

    # -----------------------------
    # client_config.json
    # -----------------------------
    config_path = root / "client_config.json"
    if not config_path.exists():
        config_path.write_text(json.dumps({
            "document_prefix": f"{client_code.upper()}_",
            "display_name": client_code,
            "parsers": {
                "nfr": "nfr_parser",
                "raids": "raids_parser",
                "actions": "actions_parser",
            },
            "templates": {
                "nfr_template": f"clients/{client_code}/templates/nfr_template.docx",
                "raid_template": f"clients/{client_code}/templates/raid_template.docx",
                "action_template": f"clients/{client_code}/templates/action_template.docx"
            },
            "dashboard": "dashboards",
            "created": datetime.utcnow().isoformat()
        }, indent=4))

    # -----------------------------
    # Parsers
    # -----------------------------
    _write_if_missing(root / "nfr_parser.py", PARSER_STUB)
    _write_if_missing(root / "raids_parser.py", RAID_PARSER_STUB)
    _write_if_missing(root / "actions_parser.py", ACTION_PARSER_STUB)

    # -----------------------------
    # Dashboard settings
    # -----------------------------
    _write_if_missing(root / "dashboards.py", DASHBOARD_STUB)

    # -----------------------------
    # Templates
    # -----------------------------
    templates = root / "templates"
    _ensure(templates)
    _write_if_missing(templates / "nfr_template.docx", PLACEHOLDER_DOCX)
    _write_if_missing(templates / "raid_template.docx", PLACEHOLDER_DOCX)
    _write_if_missing(templates / "action_template.docx", PLACEHOLDER_DOCX)

    # -----------------------------
    # Output folders for PMO tools
    # -----------------------------
    _ensure(root / "nfr" / "outputs")
    _ensure(root / "raids" / "outputs")
    _ensure(root / "actions" / "outputs")


# ------------------------------------------------------------
# Create full PROJECT folder structure
# ------------------------------------------------------------
def ensure_project_folder(client_code: str, project_code: str, metadata: dict, settings: dict):
    """
    Creates a COMPLETE PMO folder structure for a project:
    """

    root = BASE_PATH / client_code / project_code
    _ensure(root)

    # -----------------------------
    # 1. Core JSON Files
    # -----------------------------
    (root / "metadata.json").write_text(json.dumps(metadata, indent=4))
    (root / "settings.json").write_text(json.dumps(settings, indent=4))

    # -----------------------------
    # 2. RAIDs Folder
    # -----------------------------
    raids_path = root / "raids"
    _ensure(raids_path)
    _write_if_missing(raids_path / "log.json", "[]")

    # -----------------------------
    # 3. Actions Folder
    # -----------------------------
    actions_path = root / "actions"
    _ensure(actions_path)
    _write_if_missing(actions_path / "log.json", "[]")

    # -----------------------------
    # 4. NFR Folder
    # -----------------------------
    nfr_path = root / "nfr" / "history"
    _ensure(nfr_path)

    # -----------------------------
    # 5. Project Dashboards (optional)
    # -----------------------------
    dashboards_path = root / "dashboards"
    _ensure(dashboards_path)

    _write_if_missing(
        dashboards_path / "project_dashboard.json",
        json.dumps({"layout": "default", "created": datetime.utcnow().isoformat()}, indent=4)
    )

    return root


# ------------------------------------------------------------
# Delete client
# ------------------------------------------------------------
def delete_client_folder(client_code: str):
    folder = BASE_PATH / client_code
    if folder.exists():
        import shutil
        shutil.rmtree(folder)
