# modules/nfr/docx_utils.py

import os
import re
from docx import Document
from docx.shared import Pt
from docx.oxml.ns import qn
from docx.shared import RGBColor

GREEN = RGBColor(0x2E, 0xCC, 0x71)
BLACK = RGBColor(0x00, 0x00, 0x00)

# ----------------------------------------------------------------------------------------------------------------------
# Utility: delete placeholder paragraph cleanly
# ----------------------------------------------------------------------------------------------------------------------
def delete_paragraph(paragraph):
    p = paragraph._element
    parent = p.getparent()
    if parent is not None:
        parent.remove(p)
    paragraph._p = paragraph._element = None


# ----------------------------------------------------------------------------------------------------------------------
# Utility: set font on all runs in a paragraph
# ----------------------------------------------------------------------------------------------------------------------
def set_paragraph_font(paragraph, size=11, bold=False, color=None):
    for run in paragraph.runs:
        run.font.name = "Lexend Light"
        run.element.rPr.rFonts.set(qn("w:eastAsia"), "Lexend Light")
        run.font.size = Pt(size)
        run.font.bold = bold
        if color:
            run.font.color.rgb = color

# ----------------------------------------------------------------------------------------------------------------------
# Build placeholder mapping that supports both "KEY" and "{{KEY}}"
# ----------------------------------------------------------------------------------------------------------------------
def _normalise_placeholder_mapping(mapping: dict) -> dict:
    """
    Accepts overrides like:
      {"CLIENT_NAME": "Acme", "Generated By": "Mia"}
    Produces replacements for:
      {{CLIENT_NAME}}, {{ Generated By }}
    and also respects keys already wrapped like "{{CLIENT_NAME}}".
    """
    if not mapping:
        return {}

    out = {}
    for k, v in mapping.items():
        if v is None:
            v = ""
        v = str(v)

        key = str(k)

        # If caller already provided braces, keep as-is
        if key.strip().startswith("{{") and key.strip().endswith("}}"):
            out[key] = v
            continue

        # Otherwise create the {{KEY}} placeholder form
        out[f"{{{{{key}}}}}"] = v

    return out


# ----------------------------------------------------------------------------------------------------------------------
# Replace placeholders in a paragraph even if split across runs
# ----------------------------------------------------------------------------------------------------------------------
def _replace_in_paragraph(paragraph, replacements: dict):
    full_text = "".join(run.text for run in paragraph.runs)
    if not full_text:
        return

    new_text = full_text
    for ph, val in replacements.items():
        # also allow whitespace inside braces: {{ KEY }}
        if ph.startswith("{{") and ph.endswith("}}"):
            inner = ph[2:-2].strip()
            pattern = r"{{\s*" + re.escape(inner) + r"\s*}}"
            new_text = re.sub(pattern, val, new_text)
        else:
            new_text = new_text.replace(ph, val)

    if new_text != full_text:
        for r in paragraph.runs:
            r.text = ""
        # ensure there's at least one run to write into
        if paragraph.runs:
            paragraph.runs[0].text = new_text
        else:
            paragraph.add_run(new_text)

    set_paragraph_font(paragraph)


# ----------------------------------------------------------------------------------------------------------------------
# Replace placeholders in entire doc: paragraphs + tables (cells)
# ----------------------------------------------------------------------------------------------------------------------
def replace_placeholders_text(doc: Document, mapping: dict):
    """
    Replace placeholders in:
      - normal paragraphs
      - table cells (including nested tables)
    Supports mapping keys as "KEY" or "{{KEY}}".
    """
    replacements = _normalise_placeholder_mapping(mapping)

    # Body paragraphs
    for p in doc.paragraphs:
        _replace_in_paragraph(p, replacements)

    # Tables (including nested tables)
    def _walk_tables(tables):
        for table in tables:
            for row in table.rows:
                for cell in row.cells:
                    for p in cell.paragraphs:
                        _replace_in_paragraph(p, replacements)
                    # nested tables inside cells
                    if cell.tables:
                        _walk_tables(cell.tables)

    _walk_tables(doc.tables)


# ----------------------------------------------------------------------------------------------------------------------
# Formatting helpers for agent-structured JSON -> text blocks
# ----------------------------------------------------------------------------------------------------------------------
def _join_bullets(items):
    """Turn list[str] into a newline bullet list."""
    if not items:
        return ""
    return "\n".join([f"• {str(x).strip()}" for x in items if str(x).strip()])


def _format_key_discussion_points(kdps):
    """
    kdps: list of {heading:str, bullets:list[str]}
    Returns a readable text block suitable for a placeholder paragraph.
    """
    if not kdps:
        return ""
    parts = []
    for item in kdps:
        item = item or {}
        heading = str(item.get("heading", "") or "").strip()
        bullets = item.get("bullets", []) or []
        if heading:
            parts.append(heading)
        if bullets:
            parts.append(_join_bullets(bullets))
        parts.append("")  # spacing
    return "\n".join(parts).strip()


# ----------------------------------------------------------------------------------------------------------------------
# Create NFR document from agent-structured schema + overrides
# ----------------------------------------------------------------------------------------------------------------------
def create_nfr_docx(structured: dict, template_path: str, output_path: str, overrides: dict = None) -> str:
    """
    Render a DOCX from the agent-structured NFR JSON.
    - structured: agent schema (overview/objectives_agenda/attendees_table/key_discussion_points/new_actions)
    - overrides: meeting/project/client metadata used for placeholders (e.g., MEETING_NAME, DATE, TIME, LOCATION, etc.)
    """
    overrides = overrides or {}
    doc = Document(template_path)

    # -----------------------------
    # 1) Build placeholder mapping
    # -----------------------------
    overview = (structured or {}).get("overview", {}) or {}

    meeting_name = overrides.get("MEETING_NAME", "") or overrides.get("MEETING_TITLE", "") or ""
    date = overrides.get("DATE", "") or ""
    time_val = overrides.get("TIME", "") or overview.get("time", "10:00") or "10:00"
    location = overrides.get("LOCATION", "") or ""

    objectives_list = (structured or {}).get("objectives_agenda", []) or []
    kdps = (structured or {}).get("key_discussion_points", []) or []

    mapping = {
        # Header placeholders
        "{{MEETING_NAME}}": str(meeting_name),
        "{{DATE}}": str(date),
        "{{TIME}}": str(time_val),
        "{{LOCATION}}": str(location),

        # Body placeholders (text blocks)
        "{{OBJECTIVES}}": _join_bullets(objectives_list),
        "{{KEY_DISCUSSION_POINTS}}": _format_key_discussion_points(kdps),
    }

    # Pass through any other overrides as placeholders (e.g., CLIENT_NAME for {{CLIENT_NAME}})
    for k, v in overrides.items():
        if k is None:
            continue
        mapping[f"{{{{{k}}}}}"] = "" if v is None else str(v)

    replace_placeholders_text(doc, mapping)

    # -----------------------------
    # 2) Insert attendee table
    # -----------------------------
    attendees_tbl = (structured or {}).get("attendees_table", {}) or {}
    internal = attendees_tbl.get("internal", []) or []
    external = attendees_tbl.get("external", []) or []
    max_len = max(len(internal), len(external), 1)

    for p in list(doc.paragraphs):
        full_text = "".join(run.text for run in p.runs)
        if "{{ATTENDEE_TABLE}}" in full_text:
            table = doc.add_table(rows=1, cols=2)
            table.style = "Table Grid"

            hdr = table.rows[0].cells
            hdr[0].text = "Internal"
            hdr[1].text = "External"
            for cell in hdr:
                for paragraph in cell.paragraphs:
                    set_paragraph_font(paragraph, bold=True)

            for i in range(max_len):
                row = table.add_row().cells
                row[0].text = internal[i] if i < len(internal) else ""
                row[1].text = external[i] if i < len(external) else ""
                for cell in row:
                    for paragraph in cell.paragraphs:
                        set_paragraph_font(paragraph)

            p._element.addnext(table._tbl)
            delete_paragraph(p)
            break

    # -----------------------------
    # 3) Insert actions table
    # -----------------------------
    actions = (structured or {}).get("new_actions", []) or []

    for p in list(doc.paragraphs):
        full_text = "".join(run.text for run in p.runs)
        if "{{ACTIONS}}" in full_text:
            table = doc.add_table(rows=1, cols=4)
            table.style = "Table Grid"

            hdr = table.rows[0].cells
            hdr[0].text = "Title"
            hdr[1].text = "Detail"
            hdr[2].text = "Owner"
            hdr[3].text = "Due Date"
            for cell in hdr:
                for paragraph in cell.paragraphs:
                    set_paragraph_font(paragraph, bold=True)

            for a in actions:
                a = a or {}
                row = table.add_row().cells
                row[0].text = str(a.get("title", "") or "")
                row[1].text = str(a.get("detail", "") or "")
                row[2].text = str(a.get("owner", "") or "")
                row[3].text = str(a.get("due_date", "") or "")
                for cell in row:
                    for paragraph in cell.paragraphs:
                        set_paragraph_font(paragraph)

            p._element.addnext(table._tbl)
            delete_paragraph(p)
            break

    # -----------------------------
    # 4) Optional: Bold known headings
    # -----------------------------
    SECTION_HEADINGS = {
        "Objectives / Agenda",
        "Attendees",
        "Key Discussion Points",
        "New Actions",
    }

    for paragraph in doc.paragraphs:
        text = paragraph.text.strip()

        if text in SECTION_HEADINGS:
            set_paragraph_font(paragraph, bold=True, color=GREEN)
        else:
            set_paragraph_font(paragraph, color=BLACK)

    # -----------------------------
    # 5) Save
    # -----------------------------
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    doc.save(output_path)
    return output_path
